### PR TITLE
Retry npm install

### PR DESCRIPTION
**Pull request by gilmoskowitz**
extend use of the options param to runCmd to allow retrying commands if they fail, then use it to retry npm install in a few places

### CODE REVIEW

**Comment by shackbarth** [comment]
But, the xtuple-server is intended to be able to deploy different versions of xtuple-server-lib for different tasks, in dev, testing, and production. Now you're requiring that, in effect, all the other tasks be forward compatible with lib 1.2 even if they need not be.

**Comment by gilmoskowitz** [comment]
Looking at it the other way, xtuple-server-lib 1.2 has to be _backward_ compatible with 1.1 and 1.0, which is the semver definition of minor version number change. The alternative is to separate xtuple-server-lib changes from everything else and require `npm publish`ing the library before anything else dependent on it can pass CI.

**Comment by shackbarth** [comment]
It's up to each module to determine for itself how deeply they believe in using semver for their own dependencies. At the moment, they believe in semver:
https://github.com/xtuple/xtuple-server-core/blob/master/tasks/xt/install/package.json#L35
and so there's nothing specifically wrong to this approach in this case (although the threshold of lib 2.0 won't be handled well). I don't have a problem with doing it this way, but I still hold that it's safer and more technically correct, if inexpedient, to cleanly separate diffs, PRs, and npm publishes of the lib from everything else.

**Comment by gilmoskowitz** [comment]
This should start passing CI again when #507 gets merged and xtuple-server-lib 1.2.0 published.

**Pull request merged**
